language: node_js
node_js:
- '8'
install:
- npm install
before_deploy:
- npm run-script build
deploy:
  provider: npm
  script: echo "Deploying to npm..."
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    branch: master
    tags: true
